name: ttrack
version: '0.2.1'
license: UnspecifiedLicense
dependencies:
- base
library:
  source-dirs: lib
  dependencies:
  - HDBC
  - HDBC-sqlite3
  - filepath
  - time
  - network
  - MissingH
  - directory
  - parsec
  - mtl
  - microlens-platform
  - optparse-applicative
  - containers
executables:
  ttrack:
    main: Main.hs
    source-dirs: app
    ghc-options: -O2
    dependencies:
    - ttrack
    - HDBC
    - HDBC-sqlite3
    - filepath
    - network
    - directory
    - optparse-applicative
tests:
  test-ttrack:
    main: Spec.hs
    source-dirs:
    - test
    dependencies:
    - hspec
    - ttrack
    - QuickCheck
    - time
    - mtl
    - microlens-platform
    - containers
