name: ttrack
version: '0.2.1'
license: UnspecifiedLicense
dependencies:
- base
- old-locale
- mtl
- time
- parsec
- old-locale
library:
  source-dirs: lib
  dependencies:
  - HDBC
  - HDBC-sqlite3
  - filepath
  - old-time
  - network
  - MissingH
  - directory
executables:
  ttrack:
    main: Main.hs
    source-dirs: app
    ghc-options: -O2
    dependencies:
    - ttrack
    - HDBC
    - HDBC-sqlite3
    - filepath
    - old-time
    - network
    - MissingH
    - directory
tests:
  test-ttrack:
    main: Spec.hs
    source-dirs:
    - test
    - lib
    dependencies:
    - hspec
    - ttrack
    - QuickCheck
